#!/bin/bash

sudo -i
apt update
apt install curl -y
curl -O https://repo.percona.com/apt/percona-release_latest.generic_all.deb
apt install gnupg2 lsb-release ./percona-release_latest.generic_all.deb -y --allow-downgrades
apt update

# run the installation command with a timeout of 30 seconds
DEBIAN_FRONTEND=noninteractive apt-get install percona-xtradb-cluster-57 -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"


# continue with the remaining script
service mysql stop
bash -c 'echo "" > /etc/mysql/percona-xtradb-cluster.conf.d/wsrep.cnf'
bash -c 'cat <<EOT >>/etc/mysql/percona-xtradb-cluster.conf.d/wsrep.cnf
# vi /etc/mysql/percona-xtradb-cluster.conf.d/wsrep.cnf

[mysqld]
# Path to Galera library
wsrep_provider=/usr/lib/galera3/libgalera_smm.so

# Cluster connection URL contains IPs of nodes
#If no IP is found, this implies that a new cluster needs to be created,
#in order to do that you need to bootstrap this node
wsrep_cluster_address=gcomm://10.10.3.230,10.10.4.81,10.10.7.12

# In order for Galera to work correctly binlog format should be ROW
binlog_format=ROW

# MyISAM storage engine has only experimental support
default_storage_engine=InnoDB

# Slave thread to use
wsrep_slave_threads= 8

wsrep_log_conflicts

sql_mode=""
# This changes how InnoDB autoincrement locks are managed and is a requirement for Galera
innodb_autoinc_lock_mode=2

# Node IP address
wsrep_node_address=10.10.3.230
# Cluster name
wsrep_cluster_name=awsmonster

#If wsrep_node_name is not specified,  then system hostname will be used
wsrep_node_name=db1

#pxc_strict_mode allowed values: DISABLED,PERMISSIVE,ENFORCING,MASTER
pxc_strict_mode=DISABLED

# SST method
wsrep_sst_method=xtrabackup-v2

#Authentication for SST method
wsrep_sst_auth="sstuser:SST-PassWord"
EOT'


/etc/init.d/mysql bootstrap-pxc
mysql
show status like 'wsrep%';
CREATE USER 'sstuser'@'%' IDENTIFIED BY 'SST-PassWord';
GRANT RELOAD, LOCK TABLES, PROCESS, REPLICATION CLIENT ON *.* TO 'sstuser'@'%';
FLUSH PRIVILEGES;
SELECT user,authentication_string,plugin,host FROM mysql.user;



/etc/init.d/mysql start


